swagger: "2.0"
info:
  version: "0.0.1"
  title: 保險理賠 Blockchain API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  #################################################
  # Person 自然人 API    
  #################################################
  /Government/Person/:
    # binds a127 app logic to a route
    x-swagger-router-controller: Person
    get:
      description: 取得區塊鏈上已同步自然人資料
      # used as the method name of the controller
      operationId: GetPersonInfo
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TableInfo"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: 寫入自然人資料
      # used as the method name of the controller
      operationId: SetPerson
      parameters:
        - name: person
          in: body
          description: 自然人
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BlockchainTransaction"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /Government/Person/{code}:
    # binds a127 app logic to a route
    x-swagger-router-controller: Person
    get:
      description: 取得自然人最新的資料hash
      # used as the method name of the controller
      operationId: GetPersonHash
      parameters:
        - name: code
          in: path
          description: 自然人編號
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TableRowDataHash"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /Government/Person/{code}/{hash}:
    # binds a127 app logic to a route
    x-swagger-router-controller: Person
    get:
      description: 取得指定hash版本的自然人資料
      # used as the method name of the controller
      operationId: GetPersonData
      parameters:
        - name: code
          in: path
          description: 自然人編號
          required: true
          type: string
        - name: hash
          in: path
          description: 自然人資料 Hash
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Person"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  #################################################
  # Enrollment 註冊保戶保單 API        
  #################################################

  #################################################
  # ContractTerm 契約內容 API  
  #################################################

  #################################################
  # MedicalRecord 醫療記錄 API  
  #################################################

  #################################################
  # InsurancePolicy 保險契約 API   
  #################################################

  #################################################
  # ClaimRecord 理賠案件 API  
  #################################################

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  TableInfo:
    description: 區塊鏈上 RDB Table 已同步的PK資訊
    required:
      - row_count
      - row_CPKs
    properties:
      row_count:
        description: 資料比數
        type: integer
        format: int32
      row_CPKs:
        description: PK 清單
        type: array
        items:
          type: string
          
  TableRow:
    description: RDB Table row
    required:
      - row_CPK
      - row_data
    properties:
      row_CPK:
        description: RDB Table row composite PK
        type: string
      row_data:
        description: RDB Table row data
        type: string
        
  TableRowData:
    description: RDB Table row 資料
    required:
      - row_CPK
      - row_data_hash
      - row_data
    properties:
      row_CPK:
        type: string
      row_data_hash:
        type: string
      row_data:
        type: string
        
  TableRowDataHash:
    description: RDB Table row 資料hash
    required:
      - row_CPK
      - row_data_hash
    properties:
      row_CPK:
        type: string
      row_data_hash:
        type: string

  #################################################
  # Person 自然人 API Input format 
  #################################################
  Person:
    description: 自然人 data
    required:
      - table_row
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
        
  #################################################
  # Enrollment 註冊保戶保單 API Input format 
  #################################################
  Enrollment:
    description: 註冊保戶保單 data
    required:
      - table_row
      - daily_benefit_amount
      - policy_claimable_amount
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
      daily_benefit_amount:
        description: 日額保險金
        type: integer
        format: int32
      policy_claimable_amount:
        description: 保險契約可理賠額度
        type: integer
        format: int32

  #################################################
  # ContractTerm 契約內容 API data format 
  #################################################
  ContractTerm:
    description: 契約內容 data
    required:
      - table_row
      - claim_adjustment
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
      claim_adjustment:
        description: 理賠倍率 Decimal(19,9)x9
        type: integer
        format: int32

  #################################################
  # MedicalRecord 醫療記錄 API data format 
  #################################################
  MedicalRecord:
    description: 醫療記錄 data
    required:
      - table_row
      - hospital_days
      - fee
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
      hospital_days:
        description: 住院天數
        type: integer
        format: int32
      fee:
        description: 醫療費用
        type: integer
        format: int32

  #################################################
  # InsurancePolicy 保險契約 API data format 
  #################################################
  InsurancePolicy:
    description: 保險契約 data
    required:
      - table_row
      - contract_address
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
      contract_address:
        description: 契約條款智能合約地址
        type: string

  #################################################
  # ClaimRecord 理賠案件 API data format 
  #################################################
  ClaimRecord:
    description: 理賠案件 data
    required:
      - table_row
      - contract_address
    properties:
      table_row:
        $ref: "#/definitions/TableRow"
      contract_address:
        description: 契約條款智能合約地址
        type: string

  MessageResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  BlockchainTransaction:
    description: Blockchain Transaction
    required:
      - txHash
    properties:
      txHash:
        type: string
